Admin_Grouping = "//tbody//tr/td[count(//thead//th[text()='گروه‌بندی']/preceding-sibling::*)+1][not(text())]/following-sibling::td[1]"
Admin_Coupon_Type = "نوع کوپن"
Admin_Bump_Select_Btn = "css:div.card.bump"
Admin_New_Off_Code_Btn = "کد تخفیف جدید"
Admin_Coupon_Modal = "css:div.modal.in"
Admin_Discount_Percent = "id:ciscount"
Admin_Coupon_Type_css = "id:coupon_type"
Admin_Coupon_Total_Uses = "id:uses_total"
Admin_Coupon_Per_User_Uses = "id:uses_user"
Admin_Submit_Active_Coupon = "ثبت کد تخفیف فعال"
Admin_Coupon_Result = "//*[@id='coupon-results']/tbody/tr['{}']/td[3]"
Admin_Coupon_Start_Date = "id:sd"
Admin_Coupon_End_Date = "id:ed"
Admin_Calendar_Menu = "//span[@unixdate='{}']"
Admin_Calendar_Next_Month_Btn = "css=.btn-next"
Admin_New_Code_Value= "id:code"
