Chat_Section = "css:[data-test-id='mychat']"
Chat_Section_Header = "css:[data-test-id='mychat-pagetitle']"
Chat_Empty_Msg1 = "در اینجا چت‌های شما نمایش داده می‌شود."
Chat_Empty_Msg2 = "هنوز هیچ چتی ندارید."
Chat_Wall_Empty = "css:[data-test-id='chatWall-empty']"
Chat_Select_From_List_Msg = "برای شروع، یکی از چت‌ها را از لیست انتخاب کنید."
Chat_List = "css:[data-test-id='mychat-chatRooms']"
Chat_List_Item = "css:[data-test-id='mychat-chatRoom-{}']"
Chat_Load_Previous = "css:[data-test-id='chatRooms-loadMore'] >> css:button"
Chat_Item_Title = "css:[data-test-id='title-{}']"
Chat_Item_Img = "css:[data-test-id='imageContainer-{}']>img"
Chat_Item_Status = "css:[data-test-id='sp-{}']"
Chat_Item_Nickname = "css:[data-test-id='nickname-{}']"
Chat_Wall = "css:[data-test-id='mychat-chatWall']"
Chat_Wall_Container = "css:[data-test-id='chatWall-chatContainer']"
Chat_Wall_Title = "css:[data-test-id='header-title-link']"
Chat_Wall_Nickname = "css:[data-test-id='header-nickname']"
Chat_Wall_Option_Menu = "css:[data-test-id='header-three-dots']"
Chat_Wall_Option_Block = Chat_Wall_Option_Menu + " >> xpath://*[text()='بلاک']"
Chat_Wall_Send_Good_Link = "css:[data-test-id='sp10-completeFormAndSendProduction']"
Chat_Messages_Sent = "css:[data-test-id^='send-sendMessage{}']"
Chat_Msg_Sent = Chat_Messages_Sent.format('')
Chat_SP_Msg_Sent = Chat_Messages_Sent.format('-w')
Chat_Location_Sent = "css:[data-test-id^='send-sendLocation']"
Chat_Image_Sent = "css:[data-test-id^='send-sendImage']"
Chat_Received_Messages = "css:[data-test-id^='receive-sendMessage{}']"
Chat_Received_Msg = Chat_Received_Messages.format('')
Chat_SP_Received_Msg = Chat_Received_Messages.format('-w')
Chat_Received_Location = "css:[data-test-id^='receive-sendLocation']"
Chat_Received_Image = "css:[data-test-id^='receive-sendImage']"
Chat_Sheypoor_Messages = "css:[data-test-id^='message-sheypoor']"
Chat_Rating_Section = "css:[data-test-id='chatWall-rateSeller']"
Chat_Rating_To_Seller = "css:[data-test-id='rateSeller-submit']"
Chat_Rating_Popup = "css:[data-test-id='chatWall-rateSeller-popup']"
Chat_Rating_Stars = Chat_Rating_Popup + " >> css:span"
Chat_Rating_Comment = Chat_Rating_Popup + " >> css:textarea"
Chat_Rating_Register_Btn = "css:[data-test-id='rateSeller-popup-submit']"
Chat_Messages_Input = "name:msg"
Chat_Attach_Icon = "css:[data-test-id='footer-submitOrAttach']"
Chat_Send_Messages_Btn = Chat_Attach_Icon
Chat_Image_Uploader = "name:select-images-action"
Chat_Send_Image_Btn = "css:[data-test-id='imageViewer-upload']"
Chat_Address_Sender = "css:[data-test-id='attachment-locationSelect']"
Chat_Map_Popup = "css:[data-test-id='locationOnMap-popup-googleMap']"
Chat_Map_Search = "css:[data-test-id='searchbox-field']"
Chat_Map_Suggest = "css:[data-test-id='suggestion-item-{}']"
Chat_Map_Register_Btn = "css:[data-test-id='searchbox-field']"
# Chat_Permission_Popup = "popup-notif-permission-mychat"
Chat_Sp_Action_Box = "css:[data-test-id='chatWall-securePurchase']"
Chat_Sp_Msg_Box = "css:[data-test-id='messageBox-spAlert']"
Chat_Sp_Msg_1 = "فقط از طریق برنامه شیپور پرداخت کنید"
Chat_Sp_Msg_2 = "پرداخت‌هایی که از طریق شیپور انجام شوند شامل ضمانت بازگشت وجه می‌شوند. شیپور مسئولیتی در قبال پرداخت‌های خارج از خرید امن (کارت به کارت و…) ندارد."
Chat_Sp_Msg_3 = "اینجا می‌توانید با فروشنده هماهنگی‌های لازم را انجام دهید"
Chat_Sp_Icon = Chat_Sp_Msg_Box + ">span>svg"
Chat_Sp_Action_Box_Loading = Chat_Sp_Action_Box + ">span>svg"
Chat_Delivery_Time_Buyer = Chat_Sp_Action_Box + " >> css:small"
Chat_Delivery_Time_Seller = Chat_Sp_Action_Box + " >> css:strong"
Chat_Contact_Seller = "css:[data-test-id='sp10-sellerNumber']"
Chat_Contact_Support = "css:[data-test-id='{}-contactCustomerService']"
Chat_Contact_Support_Msg = "تماس با پشتیبانی"
Chat_Accept_Price = "css:[data-test-id='sp5-acceptPrice']"
Chat_Offer_New_Price = "css:[data-test-id='sp5-suggetNewPrice']"
Chat_Edit_Price = "css:[data-test-id='sp0-editPrice']"
Chat_Sp_Btn = "css:[data-test-id='sp0-securePurchase']>button"
Chat_SP_Price_Offer_Input = "name:price"
Chat_SP_Price_Offer_Submit = "css:[data-test-id='suggestNewPrice-popup-submit']"

Chat_SP_My_Chat = "css:[data-test-id='header-link-myChat']"
Chat_SP_Customer_Price_Offer_Input = "id:popup-price-suggestion >> css:input"
Chat_SP_Price_Offer_Status = "پیشنهاد قیمت"
Chat_SP_Ready_Pay_Status = "آماده پرداخت"
Chat_SP_Paid_Status = "پرداخت شده"
Chat_SP_Send_Message = "id:send-price"
Chat_SP_Sent_Price_Offer = "قیمت پیشنهادی ارسال شد"
Chat_SP_Paid_By_Buyer = "پرداخت توسط خریدار انجام شد."
Chat_Block_Reasons_Popup = "css:[data-test-id='chatBlock-reasons']"
Chat_Block_Reasons_Label = Chat_Block_Reasons_Popup + " >> xpath://label[text()='{}']"
Chat_Block_Description = Chat_Block_Reasons_Popup + " >> css:textarea"
Chat_Block_Submit = "css:[data-test-id='chatBlock-submit']"
Chat_Wall_Block = "css:[data-test-id='chatWall-userBlocked']"
Chat_Wall_Block_Msg = "شما این کاربر را بلاک کرده اید"
Chat_SP_Send_Status = "ارسال شده"
Chat_SP_Send_By_Seller_Msg = "کالا توسط شما ارسال شد"
Chat_SP_Transfer_Cost_Msg = "خریدار موظف است حداکثر تا ۳ روز پس از دریافت کالا، مطابقت آن را با آگهی ثبتی تایید کند. پس از تایید کالا یا پایان مهلت ۳ روزه، مبلغ به حساب شما منتقل خواهد شد."
Chat_SP_Wall = "css:[data-test-id='chatWall-sp{}']"
Chat_SP_Send_Goods_Msg = "اکنون برای ارسال کالا باید اطلاعات مربوط به شماره حساب و آدرس خودتان را وارد کنید."
Chat_SP_Enter_Info = "css:[data-test-id='sp10-completeFormAndSendProduction']"
Chat_SP_Enter_Info_Msg = "وارد کردن اطلاعات لازم و ارسال کالا"
Chat_SP_Conf_cont = "css:[data-test-id='sp10-confirmAndContinue']"
Chat_SP_Conf_cont_Msg = "تایید و ادامه"
Chat_SP_Other_Time = "css:[data-test-id='sp10-selectOtherDeliveryTime']"
Chat_SP_Other_Time_Msg = "انتخاب زمانی دیگر"
Chat_SP_Send_Post_Msg = "فروشنده حداکثر تا ۳ روز آینده کالا را برایتان ارسال خواهد کرد. شما می‌توانید برای هماهنگی زمان ارسال در همین صفحه به فروشنده پیام دهید. در صورت بروز مشکل با پشتیبانی تماس بگیرید."
Chat_SP_Send_Stuff_Seller_Msg = "کالا توسط فروشنده ارسال شد."
Chat_SP_Requested_Stuff_Msg = "کالای درخواستی توسط فروشنده ارسال شده است."
Chat_SP_Receive_Stuff_Msg = "پس از دریافت کالا و تایید آن روی دکمه تایید بزنید، درصورت بروز مشکل با پشتیبانی تماس بگیرید."
Chat_SP_Transfer_Funds = "css:[data-test-id='sp20-acceptAndTransfer']"
Chat_SP_Transfer_Funds_Msg = "تایید و انتقال وجه"
Chat_SP_Accept_Buy_Popup = "css:[data-test-id='sp20-acceptAndTransfer']"
Chat_SP_Commodity_Health = "css:[data-test-id='sp-acceptBuy-popup']"
Chat_SP_Commodity_Health_Msg = "کالا به دستتان رسیده و سلامت آن را تایید می‌کنید؟"
Chat_SP_Transfer_Seller_Account = "پس از تایید، مبلغ پرداختی شما به حساب فروشنده منتقل می‌شود."
Chat_SP_Accept_Buy_Submit = "css:[data-test-id='acceptBuy-popup-submit']"
Chat_SP_Wall_Nps_Popup = "css:[data-test-id='chatWall-nps-popup']"
Chat_SP_Shop_Exp_Point_Msg = "به تجربه خریدی که داشتید امتیاز دهید."
Chat_SP_Seller_Rate_Msg = "در صورتی که تا ۳ روز آینده امتیازی ثبت نکنید، به صورت خودکار به فروشنده امتیاز کامل تعلق می گیرد."
Chat_SP_Rate_To_Seller = "css:[data-test-id='sp{}-ratingToSeller']"
Chat_SP_Rate_To_Seller_Msg = "امتیاز به فروشنده"
