ML_Header = "css:[data-test-id='listing-pagetitle']"
ML_Page_Title = "آگهی‌‌های من"
ML_Active_Tab = "css:[data-test-id='listing-tab-1']"
ML_Deactive_Tab = "css:[data-test-id='listing-tab-2']"
ML_Listing = "css:[data-test-id='listing-{}']"
ML_Listing_Title = "css:[data-test-id='listing-headerlink-{}']"
ML_Edit_Listing = "css:[data-test-id='listing-edit-{}']"
ML_Delete_Listing = "css:[data-test-id='listing-delete-{}']"
ML_Delete_Popup_Listing = "css:[data-test-id='listing-delete-userinfo']"
ML_Delete_Listing_Btn = "حذف آگهی"
ML_Increase_View_Listing = "css:[data-test-id='listing-increaseview-{}']"
ML_Activate_Listing = "css:[data-test-id='listing-activate-{}']"
ML_Reassign_Listing = "css:[data-test-id='listing-reassign-{}']"
ML_Listing_Img = "css:[data-test-id='listing-img-{}'] >> css:img"
ML_Listing_Img_Count = "css:[data-test-id='listing-img-{}'] >> xpath://span/span"
ML_Listing_Status = "css:[data-test-id='listing-img-status-{}']"
ML_Listing_Price = "css:[data-test-id='listing-price-{}']"
