#PF = Paid features
#LL = Listing Limitation
#Msg = message
#L = Listing
#Pack = Package
#PM = Payment

PF_Page = "id:paid-features"
PF_Selector = "id:paid"
PF_Cancel_Btn = "انصراف"
PF_Successful_Payment = "پرداخت شما با موفقیت انجام شد"
PF_Unsuccessful_Payment = "پرداخت ناموفق"
PF_Order_Error = "خطا در سفارش"
PF_Update_Order = "بروزرسانی"
PF_Return_To_View_Increase = "بازگشت به صفحه افزایش بازدید"
PF_Unsuccessful_Payment = "عملیات پرداخت شما ناموفق بود"
PF_Total_Price = "class:total-price"
PF_Enter_Off_Code = "css:[placeholder='کد تخفیف را وارد کنید']"
PF_Payment_Btn = "css:button.payment"
PF_Operate_Off_Code = "کد تخفیف به مبلغ '{}' تومان اعمال شد."
PF_Free_Btn = "رایگان!"
PF_Update_pack_Cost = "مبلغ بسته بروزرسان"
PF_Payment_Btn_2 = "css:button.payment.pull-right"
PF_Wrong_Code = "wrongcode"
PF_Wrong_Off_Code_ = "کد وارد شده صحیح نیست"
PF_PU_Bump_Terms = "[data-popup='popup-bump-terms']"
PF_Currency_Notice = "قیمت بسته ها به تومان می باشد."
PF_Bump_PU = "popup-bump-{}"
PF_Bumps_Btn_Selector = "css:[data-popup='popup-bump']"
PF_Bump_Slider_Selector = "//label[@class='check']/span[@class='icon-checkbox-off']"
PF_L_Title = "xpath://*[@id='popup-bump']/div/div[2]/div[2]/table/tbody/tr[1]/td"
PF_Bump_Pack = "xpath://*[@id='popup-bump']/div/div[2]/div[2]/table/tbody/tr[2]/td"
PF_Apply_Discount = "xpath://*[@id='coupon']/div/button"
PF_Close_Bump = "xpath://*[@id='popup-bump']/div/div[1]/span"
PF_Discount = "xpath://*[@id='popup-bump']/div/div[2]/div[2]/table/tbody/tr[3]/td"
PF_Payable_Amount = "xpath://*[@id='popup-bump']/div/div[2]/div[2]/table/tbody/tr[4]/td"
PF_Verify_Pack = "xpath://*[@id='popup-bump-terms']/div/div[1]/span"
PF_First_Bump = "css:.serp-item.list:nth-child(1) h2 a"
PF_Bump_Header = "با امکانات زیر بازدید آگهی خود را افزایش دهید"
PF_Vitrin_Update_24 = "بروزرسانی + ۲۴ ساعت ویترین"
PF_Update_Vitrin_48 = "۲ بار بروزرسانی + ۴۸ ساعت ویتری"
PF_Cancel_GateWay = "//*[@id='button-payment-cancel']/span"
PF_Bump_Price_Selector = "xpath=//tbody//tr/td[count(//thead//th[text()='قیمت (تومان)']/preceding-sibling::*)+1]"
PF_Close_PU = "xpath://*[contains(@class, 'droppable') and contains(@class, 'open')]//div[@class='button-bar']/span"
PF_LL_Title = "css:[data-bind='text: data().listingLimit.title']"
PF_Region_Id = "id:RegionId"
PF_Purchase_Summary = "class:key-val"
PF_AllIran_Selector = "xpath://*[@id='popup-paid-all-over' and contains(@class, 'open')]//span[text()='نمایش آگهی در همه‌ی ایران']"
PF_Active_Listing = "فعال"
PF_SP_Activation_Btn = "xpath://div[@id = 'popup-secure-purchase-activation']//a[@class = 'button']"
PF_SP_Popup_Title = "xpath://div[@id = 'popup-secure-purchase-activation']//h1"
PF_SP_Popup_Title_Txt = 'با تبدیل آگهی خود به "خرید امن" سریع‌تر بفروشید.'
