SP_Shipping_Weight_Popup = "css:[data-popup='seller-info-weights']"
SP_Shipping_Weight_Value = "xpath://*[contains(@data-bind,'453306')]"        #زیر ۱ کیلو
SP_Shipping_Dimensions_Popup = "css:[data-popup='seller-info-dimensions']"
SP_Shipping_Dimensions_Value = "xpath://*[contains(@data-bind,'453313')]"        #کوچک (حمل با موتور سیکلت)
SP_Price_Input = "id:price"
SP_Nickname_Input = "id:fullName"
SP_Activation_Btn = "xpath://button[contains(text(),'فعال‌سازی خرید امن')]"
SP_Paid_Features_Page = "id:paid-features-index-page"
SP_Activation_Form = "id:secure-purchase-activation-form"
SP_Activation_Btn_Popup = "xpath://div[@id= 'popup-secure-purchase-activation']//child::a[@class = 'button']"
SP_Form = "برای فعال‌سازی خرید امن اطلاعات زیر را کامل کنید."

###################################################   CheckOut_Pages_Selectors  ##############################################################
SP_Securepurchase_Checkout_Page = "id:secure-purchase-checkout"
SP_Checkout_General_Steps = "xpath://*[@id='secure-purchase-checkout']//*[contains(@class,'general-steps')]"
SP_Checkout_General_Step_1 = SP_Checkout_General_Steps + "//*[contains(@data-bind,\"'active': step() === 1\")]"
SP_Checkout_General_Step_2 = SP_Checkout_General_Steps + "//*[contains(@data-bind,\"'active': step() === 2\")]"
SP_Checkout_General_Step_3 = SP_Checkout_General_Steps + "//*[contains(@data-bind,\"'active': step() === 3\")]"
SP_Checkout_Count_Goods = "css:[class=count]"
SP_Checkout_Listing_Content = "xpath://*[contains(@class,'listing-box')]//*[contains(@class,'content')]"
SP_Checkout_Listing_Content_Plus_Icon = SP_Checkout_Listing_Content + "//*[contains(@class,'icon-plus')]"
SP_Checkout_Listing_Content_Minus_Btn = SP_Checkout_Listing_Content + "//*[contains(@class,'icon-minus')]"
SP_Permission_Popup_Open = "xpath://*[contains(@id,'popup-permission') and contains(@class,'open')]"
SP_Permission_Ask_Close_Icon = "xpath://*[@id='popup-permission-ask']//*[contains(@class,'icon-close')]"
SP_Permission_Deny_Close_Icon = "xpath://*[@id='popup-permission-deny']//*[contains(@class,'icon-close')]"
SP_Checkout_Verify_Box = "xpath://*[contains(@class,'verify-box')]"
SP_Checkout_Shop_Icon = SP_Checkout_Verify_Box + "//*[contains(@class,'icon-secure-purchase')]"
SP_Checkout_Shop_Info = "css:[class^='seller-details']"
SP_Checkout_Receiver_Name = "xpath://input[contains(@data-bind,'fullName')]"
SP_Checkout_Delivery_Time = "css:[data-popup='popup-secure-purchase-delivery-time']"
SP_Checkout_Delivery_Times = "xpath://*[@id='popup-secure-purchase-delivery-time']//span[contains(text(),'ساعت')]"
SP_Checkout_Delivery_Times_Popup = "xpath://*[@id='popup-secure-purchase-delivery-time' and contains(@class,'open')]"
SP_Checkout_Send_Post = SP_Checkout_Delivery_Times_Popup + "//li"
SP_Checkout_Securepurchase_Address = "xpath://*[@id='secure-purchase-checkout']//*[@data-popup='popup-secure-purchase-address']"
SP_Address_Province_City = "css:[data-popup='popup-locations']"
SP_Mode_City = "class:mode-city"
SP_Suggested_Districts_Items = "xpath://*[contains(@data-bind,'mapSearch.suggests')]"
SP_Updating_Map_Loading = "css:[id='map-wrapper'][class='updating']"
SP_Submit_Address_Buttun = "xpath://*[@class='button' and contains(@data-bind,'submit')]"
SP_Search_Root_Hint = "xpath://*[contains(@class,'map-search')]//input"
SP_Map_Pin = "css:[class='snapshot']>img"
SP_Delivery_Address_Text = "id:item-form-description"
SP_Delivery_Address_Plaque = "xpath://input[contains(@data-bind,'plaque')]"
SP_Delivery_Address_Unit_Num = "xpath://input[contains(@data-bind,'unit')]"
SP_Last_Step = "xpath://*[contains(@class,'last-step')]"
SP_Checkout_User_Details = "xpath://*[@id='secure-purchase-checkout']//*[@class='user-details']"
SP_Checkout_Pay_Details = "xpath://*[@id='secure-purchase-checkout']//*[@class='pay-details']"
SP_Payment_Button = "xpath://button[contains(@class,'submit')]"
SP_Success_Payment = "id:billing"
SP_Chceckout_Purchase_Details = "xpath://*[contains(@class,'user-data-no-delivery')]"
SP_Coupon_Section = "xpath://*[@class='coupon']"
SP_Coupon_Section_Input = SP_Coupon_Section + "//input"
SP_Coupon_Section_Button = "id:couponCode"
SP_Checkout_Goods_Number_Txt = "انتخاب تعداد"
SP_Checkout_Address_Time_Txt = "آدرس و زمان"
SP_Checkout_Pay_Txt = "پرداخت"
SP_Checkout_Refund_Guarantee_Txt = "ضمانت بازگشت وجه"
SP_Checkout_Mismatch_Goods_Refund_Txt = "اگر کالای خریداری شده با مشخصات آگهی مطابقت نداشت، مبلغ پرداختی را به حسابتان برمی‌گردانیم."
SP_Checkout_Next_Step_Btn = "مرحله بعد"
SP_Checkout_Fill_Goods_Info_Step1 = "اطلاعات زیر را وارد کنید"
SP_Checkout_Select_Province = "xpath://*[contains(@class,'t-province-{}')]"
SP_Checkout_Select_City = "xpath://*[contains(@class,'t-city-{}')]"
SP_Checkout_Delivery_District = "xpath://*[contains(@data-bind,'mapSearch.suggests')]//*[contains(text(),'{}')]"
SP_Checkout_Delivery_Post = "ارسال پستی (۲ تا ۵ روز کاری)"
SP_Checkout_Post_Time_Interval = "بازه زمانی ارسال"
SP_Checkout_Fill_Goods_Info_Step2 = "لطفا این قسمت را تکمیل کنید"
SP_Checkout_Purchase_Summary_Txt = "خلاصه خرید"
SP_Checkout_Good_Name_Txt = "نام کالا"
SP_Checkout_Seller_Name_Txt = "نام فروشنده"
SP_Checkout_Order_Number_Txt = "تعداد"
SP_Checkout_Goods_Amount_Txt = "مبلغ کالا"
SP_Checkout_Delivery_Price_Txt = "هزینه ارسال"
SP_Checkout_Total_Price_Txt = "مبلغ کل"
SP_Checkout_Rules_Agreement_Txt = "با پرداخت این مبلغ شما با قوانین و مقررات شیپور موافقت کرده‌اید."
SP_Checkout_Recipient_Name_Txt = "نام تحویل گیرنده"
SP_Checkout_Recipient_Address_Txt = "آدرس تحویل گیرنده"
SP_Checkout_Delivery_Time_Txt = "زمان تحویل"
SP_Checkout_Return_Back_Txt = "اگر کالای خریداری شده با مشخصات آگهی مطابقت نداشت، مبلغ پرداختی را به حسابتان برمی‌گردانیم."
SP_Checkout_Post_By_Seller_Txt = "ارسال توسط فروشنده"
SP_Checkout_Coordination_With_Seller = "با فروشنده هماهنگی‌های لازم برای ارسال را انجام دهید، در صورتی که تا 3 روز دیگر کالا ارسال نشد مبلغ پرداختی را به حسابتان بازمیگردانیم."
SP_Checkout_Price_Offer_Txt = "توافقی با فروشنده"
SP_Checkout_Have_Coupon_Txt = "کد تخفیف دارید؟"
SP_Checkout_Send_Good_Msg = "اکنون برای ارسال کالا باید اطلاعات مربوط به شماره حساب و آدرس خودتان را وارد کنید."

# ############################################### Payment Section ##############################################
SP_Payment_Error_Message = "خطای داخلی"
SP_Payment_Successful_Message = "پرداخت با موفقیت انجام شد"
SP_Payment_Money_Blocking_Message = "مبلغ پرداختی نزد شیپور به امانت می‌ماند"
SP_Payment_Ready_For_Post_Message = "اکنون فروشنده موظف است کالا را برای شما ارسال کند، برای پیگیری ارسال کالا روی دکمه زیر بزنی"
SP_Payment_Post_Tracking = "پیگیری ارسال"

# ############################################### Secure Purchase Completion Form ##############################################
SP_Complete_Form = "id:secure-purchase-completion-form"
SP_Complete_Form_Msg = "تکمیل اطلاعات و ارسال کالا"
SP_Complete_Form_Name = "css:[data-bind='value: item.fullName']"
SP_Complete_Form_Shaba = "css:[data-bind='value: item.shaba']"
SP_Complete_Form_Sheba_Val = "IR305259273827864198421526"
SP_Complete_Form_Address = "xpath://*[@id='secure-purchase-completion-form']//*[@data-popup='popup-map']"
SP_Complete_Form_Submit_Btn = "xpath://*[@type='submit' and @class='button-bar']"
