*** Settings ***
Resource                                ../default/default-keywords.resource

*** Keywords ***
Request Alternative Neighborhoods Endpoint
    Pass Execution                      ${NOT_IMPLEMENTED_MESSAGE}

Request Deep Link Endpoint
    Pass Execution                      ${NOT_IMPLEMENTED_MESSAGE}

Request Config Endpoint
    Pass Execution                      ${NOT_IMPLEMENTED_MESSAGE}
