My_Chats="name:list-item-chat"
Chat_View="در اینجا چت‌های شما نمایش داده می‌شود"
Msg_Txt_Box_1="xpath://*[@type='text']"
Send_Msg_1="id:send-chat"

############################################# Sheypoor ################################################
Auth_Session_Position="Session"
Auth_Username_Xpath="name:username"
Auth_Post_Listiong_Position="PostListing"
Auth_Title_Login_Session_Page="ورود / ثبت نام"
Auth_Login_OR_Register_Btn="xpath://*[@type='submit']"
Auth_Code_Xpath="name:verification_code"
Auth_Login_Btn_Final_Confirm="xpath://button[@type='submit' and contains(text(),'تائید نهایی و ورود به شیپور')]"
Auth_Confirm_Code_Val="xpath://button[@type='submit']//preceding::span[1][text()='کد تایید صحیح نمی باشد']"
Auth_Complete_Field_Val="xpath://button[@type='submit']//preceding::span[1][text()='لطفا این قسمت را تکمیل کنید']"
ML_Header="css:[data-test-id='listing-pagetitle']"
ML_Page_Title="آگهی‌‌های من"
Chat_Btn="id:item-seller-details >> css:span[class*='icon-chat']"
LD_Received_Messages="css:[class='message receive']"
LD_Chat_Nickname="css:[data-bind*='nickname']"
Msg_Txt_Box_2="name:message"
Send_Msg_2="xpath://*[@type='submit']"
