FB_Menu = "list-item-file-bank"
Buy_FB_Txt = "خرید همراه فایل"
Choose_Whole_City_Txt = "انتخاب کل یک شهر"
Choose_7_Districts_Txt ="انتخاب هفت محله از یک شهر"
Province_Txt = "تهران"
Add_A_FB_Btn = "add-new-request-bank-item-empty-list-action"
Choose_FB_Package_Txt = "برای مشاهده‌ی فایل‌ها، ابتدا یکی از بسته‌های زیر را انتخاب کنید."
FB_Choose_Action_Btn = "choose-action"
FB_Choose_Area_Txt = "انتخاب محدوده"
FB_Chosen_city_Area_Txt = "شهر و محله‌های انتخابی شما"
FB_One_Month_Package_Txt = "اشتراک یک ماهه"
FB_Submit_Payment = "xpath://*[@type='submit']"
FB_Successful_Purchase_Txt = "پرداخت شما با موفقیت انجام شد."
FB_Back_Home_Page_Txt = "بازگشت به برنامه"
FB_Add_New_File_Btn = "name:add-new-file"
FB_Add_Manage_Files = "name:add-to-manage-files"
Add_New_FB_Btn = "add-new-file"
Add_FB_Btn = "xpath://*[@name='add-new-request-bank-item-empty-list-action']"
